### PR TITLE
Separate help from markdown as in #4

### PR DESCRIPTION
**Pull request by dannystaple**
This gets Issue #4 working as expected. Also check mu-editor/help for files added.

### CODE REVIEW

**Comment by carlosperate** [comment]
Correct me if I am wrong, but this will clone the https://github.com/mu-editor/help repository onto this repository root, no?
So we would still have to have all the folders for each version inside https://github.com/mu-editor/help ?


My initial though was to have use git labels to track the historical changes of the documentation and not really keep all those folders individually.

(Note that we *do not* need to do what I am about to describe, as the current documentation is pretty much all the same, but hopefully it will illustrate my though process). So the initial configuration would be:
* Have the contents of https://github.com/mu-editor/help/tree/master/0.1 in the root of the repository as a commit.
* Label such commit as "v0.1"
* Update the contents to have https://github.com/mu-editor/help/tree/master/0.9.11 in the root of the repository as a commit.
* Label such commit as "v0.9.11"
* Keep adding changes and label them in synchronisation with the Mu releases.

Then on this repository, inside the "help" folder (which would still be a real folder with a readme or something) we would have 2 git-submodules. One in would be (from root) in `help/0.1` for the commit labelled "v0.1", and the other one in `help/0.9.11` for the commit labelled "v0.9.11".

Does that make sense? I am not all that good at describing revision control concepts without drawing diagrams.

**Comment by dannystaple** [comment]
Hi Carlos, would you propose also having a help/latest submodule too? 
This seems simpler - a folder with a readme.md, and a submodule for each version.

Also - labelling commits may work, but branches may make more sense (not sure about submodule refs for a branch). My reasoning is that as documentation is fleshed out - some of that may actually be useful for older versions, or that someone may want to go fix/flesh out the help for previous versions.

**Comment by ZanderBrown** [comment]
branches of each version of Mu? that would get messy. Tags (or GitHub releases, whatever name you prefer) would be nice & tidy

**Comment by carlosperate** [comment]
>would you propose also having a help/latest submodule too?

I assume you mean within this repository, to contain the latest documentation from https://github.com/mu-editor/help? Yeah, it will depend on how we name unreleased versions of Mu. As you can see in [/mu/logic.py](https://github.com/mu-editor/mu/blob/7c6456a6256de7a7ce5ed01b9193980e582efe35/mu/logic.py#L582) we need to have the same folder name here as the version in the Python package, so that the link works. Say we decide to tag the current state as 0.9.11, we should probably change `__version__` to 0.9.12a (something along those lines) in the following commit.

> Also - labelling commits may work, but branches may make more sense (not sure about submodule refs for a branch).

I think there were some features added a couple of years ago to track specific branches, but in essence git submodules point to a specific commit independent of branches, so worse case scenario we could manually set that to whatever we want.

> My reasoning is that as documentation is fleshed out - some of that may actually be useful for older versions, or that someone may want to go fix/flesh out the help for previous versions.

That is a good point, if we wanted to add or fix stuff on the documentation from previous versions it would be easier to do so if each version had it's own branch. The only inconvenience is that we would end up with quite a few branches (as Zander has mentioned) and then we would effectively be "back porting" fixes to each branch. We'd have a similar problem with a more complex solution if we use git tag, but to be completely honest, and taking in consideration the amount of effort put so far in the Mu documentation, I don't imagine we'd be doing this very often. I don't really mind either way, I think we can make it work in both systems, it would just change the workflow.

So, as a short recap, we agree to have different submodules in this repository help folder, each pointing to a different commits to represent different versions (either from their own branch or just different points in master)?

**Comment by dannystaple** [comment]
Yup - I am happy with that idea - I'll look at making that change next.

**Comment by carlosperate** [comment]
Closing this PR as it has been superseded by https://github.com/mu-editor/mu-editor.github.io/pull/9.

**Pull request closed without merging**
