### PR TITLE
Fix #13

### LINKED ISSUE #13: Change pygments to rouge for code highlighting
From GitHub Pages: 

> The page build completed successfully, but returned the following warning:
> 
> You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml' and ensure the 'pygments' key is unset. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

So we need to updated the `_config.yml` and `Gemfile` files.

### PR DESCRIPTION
**Pull request by ZanderBrown**

### CODE REVIEW

**Comment by carlosperate** [comment]
Don't forget to update the gemfile as well ;)

**Comment by ZanderBrown** [comment]
Good catch!

**Comment by ZanderBrown** [comment]
Ping @ntoll

**Comment by ntoll** [comment]
Thank you! Keep pinging / kicking / bothering me about outstanding PRs. I'm "spinning" lots of plates at the moment so really appreciate people telling me stuff I need to be concentrating on. :-)

**Pull request merged**
