### PR TITLE
Markdown mu#150

### PR DESCRIPTION
**Pull request by dannystaple**
This converts the project to the jekyll framework. It means most editing can be made in markdown, with a little boilerplate at the top. Fancier formats can be done in html when needed. 

The theme itself is in the _includes/themes/mu folder and uses liquid templating. 
Github knows how to render this - so it should automatically pick it up and render the lot inside the templates. 

Stuff to get right:
* I added some more sample content to the help/index.md file (not the other versioned help). However - the button images may require html to style them properly.
* Not really sure where to put a sitemap/pages list - there arent yet enough there to need one I think.

### CODE REVIEW

**Comment by ZanderBrown** [comment]
Sounds good. shame we can't see it!

**Comment by dannystaple** [comment]
Zander - not quite sure what you mean there?
I think I should merge up Ntoll's latest update (the new version) before this pullrequest goes in.

**Comment by dannystaple** [comment]
Okay - turns out I'd already preempted the change of the link to the new organisation - nothing to change there.

**Comment by ntoll** [comment]
Can you rebase and resolve the conflicts?

**Comment by ZanderBrown** [comment]
@dannystaple i meant unless it's merged we cannot see it in action

**Comment by dannystaple** [comment]
Okay - rebased and resolved.

**Comment by dannystaple** [comment]
@ntoll Are you happy to merge that for me?

**Comment by ntoll** [comment]
Hah... you beat me to it. I'm currently ploughing through my email backlog and this is on my todo list. ;-)

**Comment by ntoll** [comment]
Awesomeness on stilts! :-)

**Pull request merged**
